version : "3.8"

networks:
  inception:
    driver : bridge

volumes:
  mariadb-data:
    driver: local
    driver_opts:
      o : "bind"
      type : "none"
      device : "../data/mariadb"
  wordpress-data:
    driver: local
    driver_opts:
      o : "bind"
      type : "none"
      device : "../data/wordpress"

services:
  mariadb:
    build : "./requirements/mariadb/."
    container_name: "mariadb"
    ports:
      - 3306
    networks:
        - inception
    env_file: ".env"
    volumes:
      - "mariadb-data:/var/lib/mysql"

  nginx:
    build : "./requirements/nginx/."
    container_name : "nginx"
    networks:
        - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - "wordpress-data:/var/www/html"
  
  wordpress:
    build : "./requirements/wordpress/."
    container_name : "wordpress"
    ports :
    - 9000
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - "wordpress-data:/var/www/html"
  redis:
    build : "./requirements/bonus/redis/."
    container_name : "redis"
    expose :
      - 6380
    networks:
      - inception
  adminer : 
    build : "./requirements/bonus/adminer/."
    container_name : "adminer"
    ports:
      - "80:80"
    networks:
      - inception
  ftp:
    build : "./requirements/bonus/ftp/."
    container_name : "ftp"
    ports : 
      - "21:21"
      - "40000:40000"
    networks :
      - inception
    volumes:
      - "wordpress-data:/var/www/html"
    env_file:
      - .env
    depends_on:
      - wordpress
